# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: cecile.hirschauer@bbox.fr
author_name: Cecile-Hirschauer
preset_name: starter
project_name: verifact-frontend

